### ISSUE TITLE
rust-lang package installs the toolchain into the user's HOME directory

### ISSUE THREAD

**Issue by autobakterie** [angelcam/turris-packages#4] opened 2022-05-20 16:43 UTC
https://github.com/angelcam/turris-packages/blob/77354cced6fe38c1a94501f2e229827d56e6f1e5/rust-lang/Makefile#L33-L37

As specified in the Makefile the rust-lang package host tools build process installs the toolchain inside the user's home directory (or extends an existing installation). 

This is highly unexpected from an OpenWrt package's build process. All the build outputs are expected not to land outside of OpenWrt build system directory structure and to be cleanable by variations of `make clean` command. In the current state installation of the Rust toolchain ends up being not only at the place where it should not be but being unremovable by the means of the build system as well.

Modifying directories outside of the build system tree might be seen as a marginal problem for one time builds happening e.g. in temporary single purpose VMs, but the OpenWrt and Turris OS systems are meant to be built by ordinary users on ordinary systems as well.

**Comment by operutka** [comment] 2022-05-23 11:31
Yes, this is a problem. Unfortunately, there isn't any good solution right now. It is possible to change the Rust installation directory (see https://github.com/rust-lang/rustup/issues/618) but it requires to define some environment variables every time the Rust toolchain is being used. We can definitely try it though.

I'd also like to propose a different solution that makes a lot of sense to me. Since you really care about determinism and reproducibility of your builds, I suggest using Docker. If the entire build happens inside of a Docker container, you don't have to worry about Rust being installed in user's home and you also don't need to worry about the host OS and the requirements being installed. You can simply specify everything in a Dockerfile and the only build requirement would be Docker. I can even send you a pull request as I had to dockerize your Turris Build repo for myself anyway.

**Comment by autobakterie** [comment] 2022-05-25 17:03
> Yes, this is a problem. Unfortunately, there isn't any good solution right now. It is possible to change the Rust installation directory (see rust-lang/rustup#618) but it requires to define some environment variables every time the Rust toolchain is being used. We can definitely try it though.

This sounds like a worthy try. It is also mentioned in [The rustup book](https://rust-lang.github.io/rustup/installation/index.html). Everything installed by an OpenWrt package build (even a host-only one) should end up in the `staging_dir` directory.

> I'd also like to propose a different solution that makes a lot of sense to me. Since you really care about determinism and reproducibility of your builds, I suggest using Docker. If the entire build happens inside of a Docker container, you don't have to worry about Rust being installed in user's home and you also don't need to worry about the host OS and the requirements being installed. You can simply specify everything in a Dockerfile and the only build requirement would be Docker. I can even send you a pull request as I had to dockerize your Turris Build repo for myself anyway.

Dockerizing or otherwise isolating the build by default is certainly a good idea and, as you said, might solve different problems as well, but doing this change consistently for all Turris OS builds doesn't seem like a trivial change to us. Thanks for the suggestion, nevertheless.

**Comment by operutka** [comment] 2022-05-26 10:13
> This sounds like a worthy try. It is also mentioned in [The rustup book](https://rust-lang.github.io/rustup/installation/index.html). Everything installed by an OpenWrt package build (even a host-only one) should end up in the staging_dir directory.

Ok, I'll fix this next week.

**Comment by operutka** [comment] 2022-05-30 16:57
@autobakterie please, check #5 (especially the `RUSTUP_HOME` and `CARGO_HOME` variables) and let me know if you're OK with the result.

**Comment by operutka** [comment] 2022-08-15 13:40
fixed in #5

**Closed by operutka** 2022-08-15 13:40 UTC
